# Use an official Python runtime as a parent image
FROM python:3.13-slim

# Set the working directory in the container
WORKDIR /app

# Install make utility
RUN apt-get update && apt-get install -y make git && apt-get clean

# Copy the entire project into the container
COPY . .

# Install dependencies using the Makefile
RUN make install

# Expose the HTTP server port
EXPOSE 8001

# Command to run the server using the Makefile
CMD ["make", "run-http"]