# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x11iracing.telemetry\x1a\x1cgoogle/protobuf/struct.proto\"9\n\x1cTelemetrySubscriptionRequest\x12\x0b\n\x03\x66ps\x18\x01 \x01(\r\x12\x0c\n\x04keys\x18\x02 \x03(\t\"#\n\x13GetTelemetryRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\"B\n\x14GetTelemetryResponse\x12*\n\ttelemetry\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xd9\x02\n\tTelemetry\x12\x61\n\x0cGetTelemetry\x12&.iracing.telemetry.GetTelemetryRequest\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00\x12o\n\x16RequestTelemetryStream\x12&.iracing.telemetry.GetTelemetryRequest\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00(\x01\x30\x01\x12x\n\x18SubscribeTelemetryStream\x12/.iracing.telemetry.TelemetrySubscriptionRequest\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00\x30\x01\x42\x35\n\x15\x63om.iracing.telemetryB\x15TelemetryMessageProtoP\x01\xa2\x02\x02IRb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.iracing.telemetryB\025TelemetryMessageProtoP\001\242\002\002IR'
  _globals['_TELEMETRYSUBSCRIPTIONREQUEST']._serialized_start=68
  _globals['_TELEMETRYSUBSCRIPTIONREQUEST']._serialized_end=125
  _globals['_GETTELEMETRYREQUEST']._serialized_start=127
  _globals['_GETTELEMETRYREQUEST']._serialized_end=162
  _globals['_GETTELEMETRYRESPONSE']._serialized_start=164
  _globals['_GETTELEMETRYRESPONSE']._serialized_end=230
  _globals['_TELEMETRY']._serialized_start=233
  _globals['_TELEMETRY']._serialized_end=578
# @@protoc_insertion_point(module_scope)
