# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/proto/telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server/proto/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cserver/proto/telemetry.proto\x12\x11iracing.telemetry\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"9\n\x1cTelemetrySubscriptionRequest\x12\x0b\n\x03\x66ps\x18\x01 \x01(\r\x12\x0c\n\x04keys\x18\x02 \x03(\t\"#\n\x13GetTelemetryRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\"B\n\x14GetTelemetryResponse\x12*\n\ttelemetry\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1a\n\x18GetTelemetryTypesRequest\"C\n\x19GetTelemetryTypesResponse\x12&\n\x05types\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1f\n\x1dGetTelemetryJSONSchemaRequest\"I\n\x1eGetTelemetryJSONSchemaResponse\x12\'\n\x06schema\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"6\n$GetTelemetryJSONSchemaStringResponse\x12\x0e\n\x06schema\x18\x01 \x01(\t2\xa4\x06\n\tTelemetry\x12p\n\x11GetTelemetryTypes\x12+.iracing.telemetry.GetTelemetryTypesRequest\x1a,.iracing.telemetry.GetTelemetryTypesResponse\"\x00\x12z\n\x16GetTelemetryJSONSchema\x12+.iracing.telemetry.GetTelemetryTypesRequest\x1a\x31.iracing.telemetry.GetTelemetryJSONSchemaResponse\"\x00\x12\x86\x01\n\x1cGetTelemetryJSONSchemaString\x12+.iracing.telemetry.GetTelemetryTypesRequest\x1a\x37.iracing.telemetry.GetTelemetryJSONSchemaStringResponse\"\x00\x12R\n\rDumpTelemetry\x12\x16.google.protobuf.Empty\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00\x12\x61\n\x0cGetTelemetry\x12&.iracing.telemetry.GetTelemetryRequest\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00\x12o\n\x16RequestTelemetryStream\x12&.iracing.telemetry.GetTelemetryRequest\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00(\x01\x30\x01\x12x\n\x18SubscribeTelemetryStream\x12/.iracing.telemetry.TelemetrySubscriptionRequest\x1a\'.iracing.telemetry.GetTelemetryResponse\"\x00\x30\x01\x42\x35\n\x15\x63om.iracing.telemetryB\x15TelemetryMessageProtoP\x01\xa2\x02\x02IRP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.proto.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025com.iracing.telemetryB\025TelemetryMessageProtoP\001\242\002\002IR'
  _globals['_TELEMETRYSUBSCRIPTIONREQUEST']._serialized_start=110
  _globals['_TELEMETRYSUBSCRIPTIONREQUEST']._serialized_end=167
  _globals['_GETTELEMETRYREQUEST']._serialized_start=169
  _globals['_GETTELEMETRYREQUEST']._serialized_end=204
  _globals['_GETTELEMETRYRESPONSE']._serialized_start=206
  _globals['_GETTELEMETRYRESPONSE']._serialized_end=272
  _globals['_GETTELEMETRYTYPESREQUEST']._serialized_start=274
  _globals['_GETTELEMETRYTYPESREQUEST']._serialized_end=300
  _globals['_GETTELEMETRYTYPESRESPONSE']._serialized_start=302
  _globals['_GETTELEMETRYTYPESRESPONSE']._serialized_end=369
  _globals['_GETTELEMETRYJSONSCHEMAREQUEST']._serialized_start=371
  _globals['_GETTELEMETRYJSONSCHEMAREQUEST']._serialized_end=402
  _globals['_GETTELEMETRYJSONSCHEMARESPONSE']._serialized_start=404
  _globals['_GETTELEMETRYJSONSCHEMARESPONSE']._serialized_end=477
  _globals['_GETTELEMETRYJSONSCHEMASTRINGRESPONSE']._serialized_start=479
  _globals['_GETTELEMETRYJSONSCHEMASTRINGRESPONSE']._serialized_end=533
  _globals['_TELEMETRY']._serialized_start=536
  _globals['_TELEMETRY']._serialized_end=1340
# @@protoc_insertion_point(module_scope)
